name: End-to-End tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

      - run: yarn install
        working-directory: ./Real_Estate_Website/client
            
      - run: yarn add @prisma/client
        working-directory: ./Real_Estate_Website/client
      - run: yarn add @prisma/client
        working-directory: ./Real_Estate_Website/server

      - run: yarn add express-async-handler
        working-directory: ./Real_Estate_Website/client
      - run: yarn add express-async-handler
        working-directory: ./Real_Estate_Website/server

      - name: 'Create env file'
        run: |
          touch .env
          echo PORT=4000 >> .env
          echo DATABASE_URL="mongodb+srv://johnnyaldeb:IMINhc4opL5EqF8j@cluster0.1exzuvv.mongodb.net/RealEstate?retryWrites=true&w=majority"  >> .env
          cat .env
        working-directory: ./Real_Estate_Website/server
        
      - run: yarn run dev &
        working-directory: ./Real_Estate_Website/client

      - run: yarn run start &
        working-directory: ./Real_Estate_Website/server
        
      - name: Cypress run
        uses: cypress-io/github-action@v6 
        with:
          browser: chrome
          headed: true
          working-directory: ./Real_Estate_Website/client
            
        
