name: End-to-End tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
        working-directory: ./Real_Estate_Website/client
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

      - name: install yarn
        run: yarn install

      - name: install prisma@client
        run: yarn --cwd ./Real_Estate_Website/server add @prisma/client

      - name: install express-async-handler
        run: yarn --cwd ./Real_Estate_Website/server add express-async-handler

      - name: wait for dependencies to install
        run: sleep 10
        
      - name: Start frontend & backend in background
        run: |
          yarn --cwd ./Real_Estate_Website/client run dev &
          yarn --cwd ./Real_Estate_Website/server run start &
          sleep 5
        
      - name: Cypress run
        uses: cypress-io/github-action@v6 
        with:
          browser: chrome
          build: yarn build
          start: yarn start
          headed: true
          working-directory: ./Real_Estate_Website/client
            
        
