name: End-to-End tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
        working-directory: ./Real_Estate_Website/client
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Start frontend
        run: yarn --cwd ./Real_Estate_Website/client run dev
      - name: Start backend
        run: yarn --cwd ./Real_Estate_Website/server run start
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: ./Real_Estate_Website/client
            
        
