name: End-to-End tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

      - run: cd client
      - run: pwd
      - run: yarn install
            
      - run:  cd client & pwd & yarn add @prisma/client & cd ../server & yarn add @prisma/client
      - run: pwd
      - run: yarn add @prisma/client
      - run: cd ../server
      - run: yarn add @prisma/client

      - run: cd server
      - run: pwd
      - run: yarn add express-async-handler

      - name: wait for dependencies to install
        run: sleep 2
        
      - run: cd client
      - run: pwd
      - run: yarn run dev & sleep 2

      - run: cd server
      - run: pwd
      - run: node index.js & sleep 2
        
      - name: Cypress run
        uses: cypress-io/github-action@v6 
        with:
          browser: chrome
          headed: true
          working-directory: ./Real_Estate_Website/client
            
        
