name: End-to-End tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
        working-directory: ./Real_Estate_Website/client
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          cache: 'yarn'
          cache-dependency-path: ./Real_Estate_Website/client
            
        
